export const BULK_IMPORT_TYPES = {
  PURCHASE_ORDER: "PURCHASE_ORDER",
  SUPPLIER_BILL: "SUPPLIER_BILL",
  SALES_ORDER: "SALES_ORDER",
  ESTIMATE: "ESTIMATE",
  INVOICE: "INVOICE",
  DELIVERY_CHALLAN: "DELIVERY_CHALLAN",
} as const;

export type BulkImportType = keyof typeof BULK_IMPORT_TYPES;
