export const URL_KEYS = {
  AUTH: {
    SIGNIN: "/auth/login",
    CHANGE_PASSWORD: "/auth/reset-password",
  },
  UPLOAD: {
    ADD: "/upload",
    DELETE: "/upload",
    ALL_IMAGE: "/upload/images",
    ALL_PDF: "/upload/pdf",
  },
  DASHBOARD: {
    BASE: "/dashboard",
    SALES_AND_PURCHASE_GRAPH: "/dashboard/sales-and-purchase-graph",
    TRANSACTION_GRAPH: "/dashboard/transaction-graph",
    BEST_SELLING_PRODUCTS: "/dashboard/best-selling-products",
    LEAST_SELLING_PRODUCTS: "/dashboard/least-selling-products",
    TOP_EXPENSES: "/dashboard/top-expenses",
    TOP_COUPONS: "/dashboard/top-coupons",
    RECEIVABLE: "/dashboard/receivable",
    PAYABLE: "/dashboard/payable",
    TOP_CUSTOMERS: "/dashboard/top-customers",
    CATEGORY_WISE_CUSTOMERS_COUNT: "/dashboard/category-wise-customers-count",
    CATEGORY_SALES: "/dashboard/category-sales",
    LOGIN_LOG: "/login-log/all",
    TRANSACTION: "/dashboard/transactions",
  },
  USER: {
    BASE: "/user",
    EDIT: "/user/edit",
    DROPDOWN: "/user/dropdown",
  },
  COMPANY: {
    BASE: "/company",
    ALL: "/company/all",
    ADD: "/company/add",
    EDIT: "/company/edit",
  },
  USERS: {
    BASE: "/user",
    ALL: "/user/all",
    ADD: "/user/add",
    EDIT: "/user/edit",
  },
  CONTACT: {
    BASE: "/contacts",
    DROPDOWN: "/contacts/dropdown",
    ALL: "/contacts/all",
    ADD: "/contacts/add",
    EDIT: "/contacts/edit",
  },

  BRANCH: {
    BASE: "/branch",
    DROPDOWN: "/branch/dropdown",
    ALL: "/branch/all",
    ADD: "/branch/add",
    EDIT: "/branch/edit",
  },
  BRAND: {
    BASE: "/brand",
    DROPDOWN: "/brand/dropdown",
    ALL: "/brand/all",
    ADD: "/brand/add",
    EDIT: "/brand/edit",
  },
  CATEGORY: {
    BASE: "/category",
    DROPDOWN: "/category/dropdown",
    ALL: "/category/all",
    ADD: "/category/add",
    EDIT: "/category/edit",
  },
  TAX: {
    BASE: "/tax",
    DROPDOWN: "/tax/dropdown",
    ALL: "/tax/all",
  },
  UOM: {
    BASE: "/uom",
    ALL: "/uom/all",
    DROPDOWN: "/uom/dropdown",
  },
  ROLES: {
    BASE: "/role",
    DROPDOWN: "/role/dropdown",
    ALL: "/role/all",
    ADD: "/role/add",
    EDIT: "/role/edit",
  },

  ANNOUNCEMENT: {
    ALL: "/announcement/all",
  },

  PRODUCT: {
    BASE: "/product",
    DROPDOWN: "/product/dropdown",
    ADD: "/product/add",
    ALL: "/product/all",
    EDIT: "/product/edit",
  },

  STOCK: {
    BASE: "/stock",
    ALL: "/stock/all",
    ADD: "/stock/add",
    BULK_ADJUSTMENT: "/stock/bulk-adjustment",
  },

  STOCK_VERIFICATION: {
    BASE: "/stock-verification",
    ALL: "/stock-verification/all",
    ADD: "/stock-verification/add",
    EDIT: "/stock-verification/edit",
  },

  MATERIAL_CONSUMPTION: {
    BASE: "/material-consumption",
    ALL: "/material-consumption/all",
    ADD: "/material-consumption/add",
    EDIT: "/material-consumption/edit",
  },

  CALL_REQUEST: {
    BASE: "/call-request",
    ADD: "/call-request/add",
  },
  BANK: {
    BASE: "/bank",
    DROPDOWN: "/bank/dropdown",
    ADD: "/bank/add",
    EDIT: "/bank/edit",
    ALL: "/bank/all",
  },
  PAYMENT: {
    BASE: "/payment",
    ADD: "/payment/add",
    EDIT: "/payment/edit",
    ALL: "/payment/all",
  },
  RECIPE: {
    BASE: "/recipe",
    DROPDOWN: "/recipe/dropdown",
    ADD: "/recipe/add",
    EDIT: "/recipe/edit",
    ALL: "/recipe/all",
  },
  LOCATION: {
    BASE: "/location",
    ALL: "/location/all",
    COUNTRY: "/location/country",
    STATE: "/location/state",
    CITY: "/location/city",
  },
  BILL_OF_LIVE_PRODUCT: {
    BASE: "/bill-of-live-product",
    ALL: "/bill-of-live-product/all",
    ADD: "/bill-of-live-product/add",
    EDIT: "/bill-of-live-product/edit",
  },
  PERMISSION: {
    BASE: "/permission",
    DETAILS: "/permission/details",
    CHILD: "/permission/child/details",
    ALL: "/permission/all",
    EDIT: "/permission/edit",
  },
  SUPPLIER_BILL: {
    BASE: "/supplier-bill",
    ALL: "/supplier-bill/all",
    ADD: "/supplier-bill/add",
    EDIT: "/supplier-bill/edit",
  },
  POS: {
    BASE: "/pos-order",
    HOLD_ORDER: "/pos-order/hold",
    CUSTOMER_DETAIL: "/pos-order/customer",
    ADD: "/pos-order/add",
    EDIT: "/pos-order/edit",
    DELETE: "/pos-order/delete",
  },
  POS_ORDER: {
    BASE: "/pos-order",
    ALL: "/pos-order/all",
    DROPDOWN: "/pos-order/dropdown",
    ADD: "/pos-order/add",
    EDIT: "/pos-order/edit",
    DELETE: "/pos-order/delete",
  },
  POS_PAYMENT: {
    BASE: "/pos-payment",
    ALL: "/pos-payment/all",
    ADD: "/pos-payment/add",
    EDIT: "/pos-payment/edit",
    DELETE: "/pos-payment/delete",
  },
  POS_CASH_REGISTER: {
    BASE: "/pos-cash-register",
    ALL: "/pos-cash-register/all",
    DROPDOWN: "/pos-cash-register/dropdown",
    DETAILS: "/pos-cash-register/details",
    ADD: "/pos-cash-register/add",
    EDIT: "/pos-cash-register/edit",
    DELETE: "/pos-cash-register/delete",
  },
  ADDITIONAL_CHARGES: {
    BASE: "/additional-charge",
    DROPDOWN: "/additional-charge/dropdown",
    ALL: "/additional-charge/all",
    ADD: "/additional-charge/add",
    EDIT: "/additional-charge/edit",
  },
  ACCOUNT: {
    BASE: "/account",
    DROPDOWN: "/account/dropdown",
    ALL: "/account/all",
    ADD: "/account/add",
    EDIT: "/account/edit",
  },
  ACCOUNT_GROUP: {
    BASE: "/account-group",
    DROPDOWN: "/account-group/dropdown",
    ALL: "/account-group/all",
    TREE: "/account-group/tree",
  },
  TERMS_CONDITION: {
    BASE: "/terms-condition",
    DROPDOWN: "/terms-condition/dropdown",
    ALL: "/terms-condition/all",
    ADD: "/terms-condition/add",
    EDIT: "/terms-condition/edit",
  },
  COUPON: {
    BASE: "/coupon",
    DROPDOWN: "/coupon/dropdown",
    VERIFY: "/coupon/verify",
    ALL: "/coupon/all",
    ADD: "/coupon/add",
    EDIT: "/coupon/edit",
  },
  LOYALTY: {
    BASE: "/loyalty",
    DROPDOWN: "/loyalty/dropdown",
    REDEEM: "/loyalty/redeem",
    POINTS: "/loyalty-points",
    POINTS_ADD: "/loyalty-points",
    ALL: "/loyalty/all",
    ADD: "/loyalty/add",
    EDIT: "/loyalty/edit",
  },
  PURCHASE_ORDER: {
    BASE: "/purchase-order",
    DROPDOWN: "/purchase-order/dropdown",
    ALL: "/purchase-order/all",
    ADD: "/purchase-order/add",
    EDIT: "/purchase-order/edit",
  },
  CASH_CONTROL: {
    BASE: "/cash-control",
    ALL: "/cash-control/all",
    ADD: "/cash-control/add",
    EDIT: "/cash-control/edit",
  },
  ORDER_LIST: {
    BASE: "/order-list",
    ALL: "/order-list/all",
    DROPDOWN: "/order-list/dropdown",
    ADD: "/order-list/add",
    EDIT: "/order-list/edit",
    DELETE: "/order-list/delete",
  },
  ADMIN_SETTING: {
    ALL: "/settings/all",
    UPDATE: "/settings/update",
  },
  POS_CREDIT_NOTE: {
    BASE: " ",
    ALL: "/pos-credit-note/all",
    ADD: "/pos-credit-note/add",
    EDIT: "/pos-credit-note/edit",
    DELETE: "/pos-credit-note/delete",
    REFUND: "/pos-credit-note/refund",
  },
  CREDIT_NOTE: {
    BASE: "/credit-note",
    ALL: "/credit-note/all",
    ADD: "/credit-note/add",
    EDIT: "/credit-note/edit",
    DELETE: "/credit-note/delete",
  },
  RETURN_POS_ORDER: {
    BASE: "/return-pos-order",
    ALL: "/return-pos-order/all",
    ADD: "/return-pos-order/add",
    EDIT: "/return-pos-order/edit",
    DELETE: "/return-pos-order/delete",
  },
  
  SALES_REGISTER: {
    BASE: "/sales-register",
    ADD: "/sales-register/add",
    EDIT: "/sales-register/edit",
    ALL: "/sales-register/all",
  },
} as const;
