export const URL_KEYS = {
  AUTH: {
    SIGNIN: "/auth/login",
    CHANGE_PASSWORD: "/auth/reset-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_OTP: "/auth/verify-otp",
    RESEND_OTP: "/auth/resend-otp",
    UPDATE_PASSWORD: "/auth/update-password",
  },
  UPLOAD: {
    ADD: "/upload",
    DELETE: "/upload",
    ALL_IMAGE: "/upload/images",
    ALL_PDF: "/upload/pdf",
  },
  DASHBOARD: {
    BASE: "/dashboard",
    SALES_AND_PURCHASE_GRAPH: "/dashboard/sales-and-purchase-graph",
    TRANSACTION_GRAPH: "/dashboard/transaction-graph",
    BEST_SELLING_PRODUCTS: "/dashboard/best-selling-products",
    LEAST_SELLING_PRODUCTS: "/dashboard/least-selling-products",
    TOP_EXPENSES: "/dashboard/top-expenses",
    TOP_COUPONS: "/dashboard/top-coupons",
    RECEIVABLE: "/dashboard/receivable",
    PAYABLE: "/dashboard/payable",
    TOP_CUSTOMERS: "/dashboard/top-customers",
    CATEGORY_WISE_CUSTOMERS_COUNT: "/dashboard/category-wise-customers-count",
    CATEGORY_SALES: "/dashboard/category-sales",
    LOGIN_LOG: "/login-log/all",
    TRANSACTION: "/dashboard/transactions",
  },
  USER: {
    BASE: "/user",
    EDIT: "/user/edit",
    DROPDOWN: "/user/dropdown",
  },
  COMPANY: {
    BASE: "/company",
    ALL: "/company/all",
    ADD: "/company/add",
    EDIT: "/company/edit",
  },
  USERS: {
    BASE: "/user",
    ALL: "/user/all",
    ADD: "/user/add",
    EDIT: "/user/edit",
  },
  CONTACT: {
    BASE: "/contacts",
    DROPDOWN: "/contacts/dropdown",
    ALL: "/contacts/all",
    ADD: "/contacts/add",
    EDIT: "/contacts/edit",
    BULK_ADD: "/contacts/bulk-add",
  },

  BRANCH: {
    BASE: "/branch",
    DROPDOWN: "/branch/dropdown",
    ALL: "/branch/all",
    ADD: "/branch/add",
    EDIT: "/branch/edit",
    REPORT_FORMAT: "/branch/report-config",
  },
  BRAND: {
    BASE: "/brand",
    DROPDOWN: "/brand/dropdown",
    ALL: "/brand/all",
    ADD: "/brand/add",
    EDIT: "/brand/edit",
  },
  CATEGORY: {
    BASE: "/category",
    DROPDOWN: "/category/dropdown",
    ALL: "/category/all",
    ADD: "/category/add",
    EDIT: "/category/edit",
  },
  TAX: {
    BASE: "/tax",
    DROPDOWN: "/tax/dropdown",
    ALL: "/tax/all",
    ADD: "/tax/add",
    EDIT: "/tax/edit",
    DELETE: "/tax/delete",
  },
  UOM: {
    BASE: "/uom",
    ALL: "/uom/all",
    DROPDOWN: "/uom/dropdown",
  },
  ROLES: {
    BASE: "/role",
    DROPDOWN: "/role/dropdown",
    ALL: "/role/all",
    ADD: "/role/add",
    EDIT: "/role/edit",
  },

  PREFIX: {
    BASE: "/prefix",
    DROPDOWN: "/prefix/dropdown",
    ALL: "/prefix/all",
    ADD: "/prefix/add",
    EDIT: "/prefix/edit",
  },
  PAYMENT_TERM: {
    BASE: "/payment-term",
    DROPDOWN: "/payment-term/dropdown",
    ALL: "/payment-term/all",
    ADD: "/payment-term/add",
    EDIT: "/payment-term/edit",
  },
  CONSUMPTION_TYPE: {
    BASE: "/consumption-type",
    DROPDOWN: "/consumption-type/dropdown",
    ALL: "/consumption-type/all",
    ADD: "/consumption-type/add",
    EDIT: "/consumption-type/edit",
  },

  ANNOUNCEMENT: {
    ALL: "/announcement/all",
  },

  PRODUCT: {
    BASE: "/product",
    DROPDOWN: "/product/dropdown",
    ADD: "/product/add",
    ALL: "/product/all",
    EDIT: "/product/edit",
    DETECT: "/product/detect",
    BULK_ADD: "/product/bulk-add",
  },

  STOCK: {
    BASE: "/stock",
    ALL: "/stock/all",
    ADD: "/stock/add",
    BULK_ADJUSTMENT: "/stock/bulk-adjustment",
  },

  STOCK_VERIFICATION: {
    BASE: "/stock-verification",
    ALL: "/stock-verification/all",
    ADD: "/stock-verification/add",
    EDIT: "/stock-verification/edit",
  },

  MATERIAL_CONSUMPTION: {
    BASE: "/material-consumption",
    ALL: "/material-consumption/all",
    ADD: "/material-consumption/add",
    EDIT: "/material-consumption/edit",
  },

  CALL_REQUEST: {
    BASE: "/call-request",
    ADD: "/call-request/add",
  },
  BANK: {
    BASE: "/bank",
    DROPDOWN: "/bank/dropdown",
    ADD: "/bank/add",
    EDIT: "/bank/edit",
    ALL: "/bank/all",
  },
  PAYMENT: {
    BASE: "/payment",
    ADD: "/payment/add",
    EDIT: "/payment/edit",
    ALL: "/payment/all",
  },
  RECIPE: {
    BASE: "/recipe",
    DROPDOWN: "/recipe/dropdown",
    ADD: "/recipe/add",
    EDIT: "/recipe/edit",
    ALL: "/recipe/all",
  },
  LOCATION: {
    BASE: "/location",
    ALL: "/location/all",
    COUNTRY: "/location/country",
    STATE: "/location/state",
    CITY: "/location/city",
  },
  BILL_OF_LIVE_PRODUCT: {
    BASE: "/bill-of-live-product",
    ALL: "/bill-of-live-product/all",
    ADD: "/bill-of-live-product/add",
    EDIT: "/bill-of-live-product/edit",
  },
  PERMISSION: {
    BASE: "/permission",
    DETAILS: "/permission/details",
    CHILD: "/permission/child/details",
    ALL: "/permission/all",
    EDIT: "/permission/edit",
  },
  SUPPLIER_BILL: {
    BASE: "/supplier-bill",
    ALL: "/supplier-bill/all",
    ADD: "/supplier-bill/add",
    EDIT: "/supplier-bill/edit",
    DROPDOWN: "/supplier-bill/dropdown",
  },
  POS: {
    BASE: "/pos-order",
    HOLD_ORDER: "/pos-order/hold",
    CUSTOMER_DETAIL: "/pos-order/customer",
    ADD: "/pos-order/add",
    EDIT: "/pos-order/edit",
    DELETE: "/pos-order/delete",
  },
  POS_ORDER: {
    BASE: "/pos-order",
    ALL: "/pos-order/all",
    DROPDOWN: "/pos-order/dropdown",
    ADD: "/pos-order/add",
    EDIT: "/pos-order/edit",
    DELETE: "/pos-order/delete",
  },
  POS_PAYMENT: {
    BASE: "/pos-payment",
    ALL: "/pos-payment/all",
    ADD: "/pos-payment/add",
    EDIT: "/pos-payment/edit",
    DELETE: "/pos-payment/delete",
    PENDING_PAYMENT_DROPDOWN: "/pos-payment/pending-payment/dropdown",
    PENDING_CREDIT_DROPDOWN: "/pos-payment/pending-credit/dropdown",
  },
  POS_CASH_REGISTER: {
    BASE: "/pos-cash-register",
    ALL: "/pos-cash-register/all",
    DROPDOWN: "/pos-cash-register/dropdown",
    DETAILS: "/pos-cash-register/details",
    ADD: "/pos-cash-register/add",
    EDIT: "/pos-cash-register/edit",
    DELETE: "/pos-cash-register/delete",
  },
  ADDITIONAL_CHARGES: {
    BASE: "/additional-charge",
    DROPDOWN: "/additional-charge/dropdown",
    ALL: "/additional-charge/all",
    ADD: "/additional-charge/add",
    EDIT: "/additional-charge/edit",
  },
  TERMS_CONDITION: {
    BASE: "/terms-condition",
    DROPDOWN: "/terms-condition/dropdown",
    ALL: "/terms-condition/all",
    ADD: "/terms-condition/add",
    EDIT: "/terms-condition/edit",
  },
  COUPON: {
    BASE: "/coupon",
    DROPDOWN: "/coupon/dropdown",
    VERIFY: "/coupon/verify",
    ALL: "/coupon/all",
    ADD: "/coupon/add",
    EDIT: "/coupon/edit",
  },
  LOYALTY: {
    BASE: "/loyalty",
    DROPDOWN: "/loyalty/dropdown",
    REDEEM: "/loyalty/redeem",
    POINTS: "/loyalty-points",
    POINTS_ADD: "/loyalty-points",
    ALL: "/loyalty/all",
    ADD: "/loyalty/add",
    EDIT: "/loyalty/edit",
  },
  DISCOUNT: {
    BASE: "/discount",
    DROPDOWN: "/discount/dropdown",
    VERIFY: "/discount/verify",
    ALL: "/discount/all",
    ADD: "/discount/add",
    EDIT: "/discount/edit",
  },
  PURCHASE_ORDER: {
    BASE: "/purchase-order",
    DROPDOWN: "/purchase-order/dropdown",
    ALL: "/purchase-order/all",
    ADD: "/purchase-order/add",
    EDIT: "/purchase-order/edit",
  },
  CASH_CONTROL: {
    BASE: "/cash-control",
    ALL: "/cash-control/all",
    ADD: "/cash-control/add",
    EDIT: "/cash-control/edit",
  },
  ORDER_LIST: {
    BASE: "/order-list",
    ALL: "/order-list/all",
    DROPDOWN: "/order-list/dropdown",
    ADD: "/order-list/add",
    EDIT: "/order-list/edit",
    DELETE: "/order-list/delete",
  },
  ADMIN_SETTING: {
    ALL: "/settings/all",
    UPDATE: "/settings/update",
  },

  REPORT_FORMAT: {
    BASE: "/report-format",
    ALL: "/report-format/all",
    ADD: "/report-format/add",
    EDIT: "/report-format/edit",
  },
  POS_CREDIT_NOTE: {
    BASE: "/pos-credit-note",
    ALL: "/pos-credit-note/all",
    ADD: "/pos-credit-note/add",
    EDIT: "/pos-credit-note/edit",
    DELETE: "/pos-credit-note/delete",
    REFUND: "/pos-credit-note/refund",
    REDEEM: "/pos-credit-note/redeem",
    REDEEM_DROPDOWN: "/pos-credit-note/redeem-dropdown",
    DROPDOWN: "/pos-credit-note/dropdown",
  },
  CREDIT_NOTE: {
    BASE: "/credit-note",
    ALL: "/credit-note/all",
    ADD: "/credit-note/add",
    EDIT: "/credit-note/edit",
    DELETE: "/credit-note/delete",
  },
  DEBIT_NOTE: {
    BASE: "/debit-note",
    ALL: "/debit-note/all",
    ADD: "/debit-note/add",
    EDIT: "/debit-note/edit",
    DELETE: "/debit-note/delete",
  },
  RETURN_POS_ORDER: {
    BASE: "/return-pos-order",
    ALL: "/return-pos-order/all",
    ADD: "/return-pos-order/add",
    EDIT: "/return-pos-order/edit",
    DELETE: "/return-pos-order/delete",
  },

  SALES_REGISTER: {
    BASE: "/sales-register",
    ADD: "/sales-register/add",
    EDIT: "/sales-register/edit",
    ALL: "/sales-register/all",
  },
  PURCHASE_DEBIT_NOTE: {
    BASE: "/purchase-debit-note",
    ALL: "/purchase-debit-note/all",
    DROPDOWN: "/purchase-debit-note/dropdown",
    ADD: "/purchase-debit-note/add",
    EDIT: "/purchase-debit-note/edit",
  },
  EXPENSE: {
    BASE: "/expense",
    ALL: "/expense/all",
    ADD: "/expense/add",
    EDIT: "/expense/edit",
    DELETE: "/expense/delete",
  },

  //*************** Estimate **************** */
  ESTIMATE: {
    BASE: "/estimate",
    ALL: "/estimate/all",
    ADD: "/estimate/add",
    EDIT: "/estimate/edit",
    DELETE: "/estimate/delete",
    DROPDOWN: "/estimate/dropdown",
  },

  //*************** Sales Order **************** */
  SALES_ORDER: {
    BASE: "/sales-order",
    ALL: "/sales-order/all",
    ADD: "/sales-order/add",
    EDIT: "/sales-order/edit",
    DELETE: "/sales-order/delete",
    DROPDOWN: "/sales-order/dropdown",
  },

  //*************** Invoice **************** */
  INVOICE: {
    BASE: "/invoice",
    ALL: "/invoice/all",
    ADD: "/invoice/add",
    EDIT: "/invoice/edit",
    DELETE: "/invoice/delete",
    DROPDOWN: "/invoice/dropdown",
  },
  //*************** Delivery Challan **************** */
  DELIVERY_CHALLAN: {
    BASE: "/delivery-challan",
    ALL: "/delivery-challan/all",
    ADD: "/delivery-challan/add",
    EDIT: "/delivery-challan/edit",
    DELETE: "/delivery-challan/delete",
    DROPDOWN: "/delivery-challan/dropdown",
  },
  SALES_CREDIT_NOTE: {
    BASE: "/sales-credit-note",
    ALL: "/sales-credit-note/all",
    ADD: "/sales-credit-note/add",
    EDIT: "/sales-credit-note/edit",
    DELETE: "/sales-credit-note/delete",
    DROPDOWN: "/sales-credit-note/dropdown",
    ADD_EDIT: "/sales-credit-note/add-edit",
  },
  SALARY: {
    BASE: "/salary",
    ALL: "/salary/all",
    ADD: "/salary/add",
    EDIT: "/salary/edit",
    DELETE: "/salary/delete",
  },
  BANK_TRANSACTION: {
    BASE: "/bank-transaction",
    ADD: "/bank-transaction/add",
    EDIT: "/bank-transaction/edit",
    ALL: "/bank-transaction/all",
    DROPDOWN: "/bank-transaction/dropdown",
  },
  STOCK_TRANSFER: {
    BASE: "/stock-transfer",
    ALL: "/stock-transfer/all",
    REQUEST: "/stock-transfer/request",
    EDIT: "/stock-transfer/edit",
    DELETE: "/stock-transfer/delete",
    APPROVE: "/stock-transfer/approve",
    REJECT: "/stock-transfer/reject",
    CONFIRM_RECEIPT: "/stock-transfer/confirm-receipt",
    DISPATCH: "/stock-transfer/dispatch",
  },

  NOTIFICATION: {
    BASE: "/notification",
    ALL: "/notification/all",
    READ: "/notification/read",
    READ_ALL: "/notification/read-all",
    DELETE: "/notification/delete",
  },
} as const;
