export const URL_KEYS = {
  AUTH: {
    SIGNIN: "/auth/login",
  },
  UPLOAD: {
    ADD: "/upload",
    DELETE: "/upload",
    ALL_IMAGE: "/upload/images",
    ALL_PDF: "/upload/pdf",
  },
  USER: {
    BASE: "/user",
    EDIT: "/user/edit",
    DROPDOWN: "/user/dropdown",
  },
  COMPANY: {
    BASE: "/company",
    ALL: "/company/all",
    ADD: "/company/add",
    EDIT: "/company/edit",
  },
  USERS: {
    BASE: "/user",
    ALL: "/user/all",
    ADD: "/user/add",
    EDIT: "/user/edit",
  },
  CONTACT: {
    BASE: "/contacts",
    DROPDOWN: "/contacts/dropdown",
    ALL: "/contacts/all",
    ADD: "/contacts/add",
    EDIT: "/contacts/edit",
  },

  BRANCH: {
    BASE: "/branch",
    DROPDOWN: "/branch/dropdown",
    ALL: "/branch/all",
    ADD: "/branch/add",
    EDIT: "/branch/edit",
  },
  BRAND: {
    BASE: "/brand",
    DROPDOWN: "/brand/dropdown",
    ALL: "/brand/all",
    ADD: "/brand/add",
    EDIT: "/brand/edit",
  },
  CATEGORY: {
    BASE: "/category",
    DROPDOWN: "/category/dropdown",
    ALL: "/category/all",
    ADD: "/category/add",
    EDIT: "/category/edit",
  },
  TAX: {
    BASE: "/tax",
    DROPDOWN: "/tax/dropdown",
    ALL: "/tax/all",
  },
  UOM: {
    BASE: "/uom",
    ALL: "/uom/all",
    DROPDOWN: "/uom/dropdown",
  },
  ROLES: {
    BASE: "/role",
    DROPDOWN: "/role/dropdown",
    ALL: "/role/all",
    ADD: "/role/add",
    EDIT: "/role/edit",
  },

  ANNOUNCEMENT: {
    ALL: "/announcement/all",
  },

  PRODUCT: {
    BASE: "/product",
    DROPDOWN: "/product/dropdown",
    ADD: "/product/add",
    ALL: "/product/all",
    EDIT: "/product/edit",
  },

  STOCK: {
    BASE: "/stock",
    ALL: "/stock/all",
    ADD: "/stock/add",
    BULK_ADJUSTMENT: "/stock/bulk-adjustment",
  },

  STOCK_VERIFICATION: {
    BASE: "/stock-verification",
    ALL: "/stock-verification/all",
    ADD: "/stock-verification/add",
    EDIT: "/stock-verification/edit",
  },

  MATERIAL_CONSUMPTION: {
    BASE: "/material-consumption",
    ALL: "/material-consumption/all",
    ADD: "/material-consumption/add",
    EDIT: "/material-consumption/edit",
  },

  CALL_REQUEST: {
    BASE: "/call-request",
    ADD: "/call-request/add",
  },
  BANK: {
    BASE: "/bank",
    DROPDOWN: "/bank/dropdown",
    ADD: "/bank/add",
    EDIT: "/bank/edit",
    ALL: "/bank/all",
  },
  PAYMENT: {
    BASE: "/payment",
    ADD: "/payment/add",
    EDIT: "/payment/edit",
    ALL: "/payment/all",
  },
  RECIPE: {
    BASE: "/recipe",
    DROPDOWN: "/recipe/dropdown",
    ADD: "/recipe/add",
    EDIT: "/recipe/edit",
    ALL: "/recipe/all",
  },
  LOCATION: {
    BASE: "/location",
    ALL: "/location/all",
    COUNTRY: "/location/country",
    STATE: "/location/state",
    CITY: "/location/city",
  },
  BILL_OF_LIVE_PRODUCT: {
    BASE: "/bill-of-live-product",
    ALL: "/bill-of-live-product/all",
    ADD: "/bill-of-live-product/add",
    EDIT: "/bill-of-live-product/edit",
  },
  PERMISSION: {
    BASE: "/permission",
    DETAILS: "/permission/details",
    CHILD: "/permission/child/details",
    ALL: "/permission/all",
    EDIT: "/permission/edit",
  },
  SUPPLIER_BILL: {
    BASE: "/supplier-bill",
    ALL: "/supplier-bill/all",
    ADD: "/supplier-bill/add",
    EDIT: "/supplier-bill/edit",
  },
  POS: {
    BASE: "/pos-order",
    HOLD_ORDER: "/pos-order/hold",
    CUSTOMER_DETAIL: "/pos-order/customer",
    ADD: "/pos-order/add",
    EDIT: "/pos-order/edit",
    DELETE: "/pos-order/delete",
  },
  POS_ORDER: {
    BASE: "/pos-order",
    ALL: "/pos-order/all",
    DROPDOWN: "/pos-order/dropdown",
    ADD: "/pos-order/add",
    EDIT: "/pos-order/edit",
    DELETE: "/pos-order/delete",
  },
  POS_PAYMENT: {
    BASE: "/pos-payment",
    ALL: "/pos-payment/all",
    ADD: "/pos-payment/add",
    EDIT: "/pos-payment/edit",
    DELETE: "/pos-payment/delete",
  },
  ADDITIONAL_CHARGES: {
    BASE: "/additional-charge",
    DROPDOWN: "/additional-charge/dropdown",
    ALL: "/additional-charge/all",
    ADD: "/additional-charge/add",
    EDIT: "/additional-charge/edit",
  },
  ACCOUNT: {
    BASE: "/account",
    DROPDOWN: "/account/dropdown",
    ALL: "/account/all",
    ADD: "/account/add",
    EDIT: "/account/edit",
  },
  ACCOUNT_GROUP: {
    BASE: "/account-group",
    DROPDOWN: "/account-group/dropdown",
    ALL: "/account-group/all",
  },
  TERMS_CONDITION: {
    BASE: "/terms-condition",
    DROPDOWN: "/terms-condition/dropdown",
    ALL: "/terms-condition/all",
    ADD: "/terms-condition/add",
    EDIT: "/terms-condition/edit",
  },
  COUPON: {
    BASE: "/coupon",
    DROPDOWN: "/coupon/dropdown",
    VERIFY: "/coupon/verify",
    ALL: "/coupon/all",
    ADD: "/coupon/add",
    EDIT: "/coupon/edit",
  },
  LOYALTY: {
    BASE: "/loyalty",
    DROPDOWN: "/loyalty/dropdown",
    REDEEM: "/loyalty/redeem",
    POINTS: "/loyalty-points",
    POINTS_ADD: "/loyalty-points",
    ALL: "/loyalty/all",
    ADD: "/loyalty/add",
    EDIT: "/loyalty/edit",
  },
  PURCHASE_ORDER: {
    BASE: "/purchase-order",
    DROPDOWN: "/purchase-order/dropdown",
    ALL: "/purchase-order/all",
    ADD: "/purchase-order/add",
    EDIT: "/purchase-order/edit",
  },
  CASH_CONTROL: {
    BASE: "/cash-control",
    ALL: "/cash-control/all",
    ADD: "/cash-control/add",
    EDIT: "/cash-control/edit",
  },
} as const;
